### ISSUE TITLE
Decode quoted-printable, and unescape entities

### ISSUE THREAD

**Issue by vovkkk** [vladimarius/imapy#12] opened 2015-12-24 08:43 UTC
I’m not sure if this should be done by default, but at least it worth to share here and maybe in docs/notes (since it take some time to figure out, so maybe following code will help other newbies)

``` python
import quopri, HTMLParser

try:
    html = [quopri.decodestring(p).decode('utf8') for p in email["html"]]
except:
    html = [p.decode('utf8') for p in email["html"]]

html_parser = HTMLParser.HTMLParser()
try:
    text = [quopri.decodestring(p).decode('utf8') for p in email["text"]]
except:
    text = [p["text"].decode('utf8') for p in email["text"]]
finally:
    text = [html_parser.unescape(p) for p in text]
```

Docs: [quopri](https://docs.python.org/2/library/quopri.html), [HTMLParser.HTMLParser.unescape](https://hg.python.org/cpython/file/2.7/Lib/HTMLParser.py#l447)

**Comment by vladimarius** [comment] 2015-12-24 12:44
How is that related to imapy lib ?

**Comment by vovkkk** [comment] 2015-12-24 13:52
Well, this code gives _readable_ (or usable) html and text from email object of imapy lib.
I had to fiddle around for some time to figure it out.
So I think it worth to share. Esp. since some message has empty html key, but text key is actually html instead of plain text.

**Comment by vladimarius** [comment] 2015-12-24 21:35
I am closing this since it's not related to imapy functionality and is not a bug

**Closed as completed by vladimarius** 2015-12-24 21:35 UTC
