### ISSUE TITLE
error trying a simple script

### ISSUE THREAD

**Issue by zemadmat** [vladimarius/imapy#5] opened 2015-09-13 20:00 UTC
hi,

i'm trying a simple script but it ends with the following error:

Traceback (most recent call last):
  File "checkmail4.py", line 12, in <module>
    ssl=True)
  File "/usr/local/lib/python2.7/dist-packages/imapy/connector.py", line 19, in connect
    imapy = imap.IMAP()
  File "/usr/local/lib/python2.7/dist-packages/imapy/imap.py", line 67, in **init**
    self.mail_folder_class = MailFolder()
  File "/usr/local/lib/python2.7/dist-packages/imapy/mail_folder.py", line 39, in **init**
    ''', re.VERBOSE)
  File "/usr/lib/python2.7/re.py", line 190, in compile
    return _compile(pattern, flags)
  File "/usr/lib/python2.7/re.py", line 242, in _compile
    raise error, v # invalid expression
sre_constants.error: nothing to repeat

the script is 

``` python
# -*- encoding: utf-8 -*-
"""
Shows some basic operations with Imapy
"""
import imapy
box = imapy.connect(
    host='imap.gmail.com',
    username='username@gmail.com',
    password='secret',
    ssl=True)
names = box.folders()
emails = box.folder('Inbox').emails(-5)
for email in emails:
    print(email['from'], email['subject'])
```

can you help ?

cheers

**Comment by vladimarius** [comment] 2015-09-14 07:54
What Python version are you using ?
My guess is that you are using Python having version < 2.7.6
See https://github.com/vladimarius/imapy/issues/2

**Comment by zemadmat** [comment] 2015-09-14 21:36
yes i'm using python 2.7.3 and unfortunatly i do not have a newer version available. i'm using a raspberry pi.

**Comment by woutervh** [comment] 2015-10-10 23:12
This is a duplicate of #2

**Closed as completed** 2015-11-22 13:54 UTC
